# **TO - DO - Task**
# AI and Machine Learning - Worksheet 0
#Krishal Maharjan
#2408955
# **4.1 Exercise on Functions:**


**Task - 1: Create a Python program that converts between different units of measurement.**

**• The program should:**
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

**• Requirements:**
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

**• Conversion Options:**
1. Length:
 Convert meters (m) to feet (ft).
 Convert feet (ft) to meters (m).
2. Weight:
 Convert kilograms (kg) to pounds (lbs).
 Convert pounds (lbs) to kilograms (kg).
3. Volume:
 Convert liters (L) to gallons (gal).
 Convert gallons (gal) to liters (L).


In [ ]:
def convert_units(conversion_type, value):
    """
    Converts units based on selected conversion type.

    Parameters:
    conversion_type (str): Type of conversion
    value (float): Value to convert

    Returns:
    float: Converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type")


try:
    print("Choose conversion:")
    print("1. meters to feet")
    print("2. feet to meters")
    print("3. kg to pounds")
    print("4. pounds to kg")
    print("5. liters to gallons")
    print("6. gallons to liters")

    choice = int(input("Enter choice: "))
    value = float(input("Enter value to convert: "))

    conversions = {
        1: "m_to_ft",
        2: "ft_to_m",
        3: "kg_to_lbs",
        4: "lbs_to_kg",
        5: "l_to_gal",
        6: "gal_to_l"
    }

    result = convert_units(conversions[choice], value)
    print("Converted value:", result)

except ValueError:
    print("Invalid input. Please enter numeric values.")
except KeyError:
    print("Invalid conversion choice.")

Choose conversion:
1. meters to feet
2. feet to meters
3. kg to pounds
4. pounds to kg
5. liters to gallons
6. gallons to liters
Enter choice: 1
Enter value to convert: 3
Converted value: 9.84252


**Task - 2: Create a Python program that performs various mathematical operations on a list of numbers.**

**• The Program should:**
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

**• Requirements:**
1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.


In [ ]:
def find_sum(numbers):
    """Returns the sum of numbers."""
    return sum(numbers)


def find_average(numbers):
    """Returns the average of numbers."""
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """Returns the maximum number."""
    return max(numbers)


def find_min(numbers):
    """Returns the minimum number."""
    return min(numbers)


try:
    nums = input("Enter numbers separated by space: ")
    numbers = list(map(float, nums.split()))

    if len(numbers) == 0:
        raise ValueError("Empty list")

    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = int(input("Enter choice: "))

    if choice == 1:
        print("Sum:", find_sum(numbers))
    elif choice == 2:
        print("Average:", find_average(numbers))
    elif choice == 3:
        print("Maximum:", find_max(numbers))
    elif choice == 4:
        print("Minimum:", find_min(numbers))
    else:
        print("Invalid operation")

except ValueError:
    print("Invalid input.")

Enter numbers separated by space: 55 77
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 3
Maximum: 77.0


# 4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
 Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
 Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """Returns every other element starting from first."""
    return lst[::2]


def get_sublist(lst, start, end):
    """Returns sublist from start to end inclusive."""
    return lst[start:end+1]


def reverse_list(lst):
    """Returns reversed list using slicing."""
    return lst[::-1]


def remove_first_last(lst):
    """Removes first and last elements."""
    return lst[1:-1]


def get_first_n(lst, n):
    """Returns first n elements."""
    return lst[:n]


def get_last_n(lst, n):
    """Returns last n elements."""
    return lst[-n:]


def reverse_skip(lst):
    """Returns elements in reverse skipping one."""
    return lst[-2::-2]

data = [1,2,3,4,5,6]
print(extract_every_other(data))

[1, 3, 5]


2. **Slice a Sublist:**
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
**• Requirements:**
 Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
 Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
print(get_sublist(data,2,4))

[3, 4, 5]


3. **Reverse a List Using Slicing:**
Write a Python function that reverses a list using slicing.
**• Requirements:**
 Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
 Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

19


In [ ]:
print(reverse_list(data))

[6, 5, 4, 3, 2, 1]


4. **Remove the First and Last Elements:**
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
**• Requirements:**
 Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
 Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
print(remove_first_last(data))

[2, 3, 4, 5]


5. **Get the First n Elements:**
Write a Python function that extracts the first n elements from a list.
**• Requirements:**
 Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
 Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
print(get_first_n(data,3))

[1, 2, 3]


6. **Extract Elements from the End:**
Write a Python function that extracts the last n elements of a list using slicing.
**• Requirements:**
 Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
 Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
print(get_last_n(data,2))

[5, 6]


7. **Extract Elements in Reverse Order:**
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
**• Requirements:**
 Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
 Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

20


In [ ]:
print(reverse_skip(data))

[5, 3, 1]


# 4.3 Exercise on Nested List:

**1. Flatten a Nested List:**
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
**• Requirements:**
 Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
 Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].


In [ ]:
def flatten(lst):
    """Flattens one level nested list."""
    result = []
    for i in lst:
        result.extend(i)
    return result


def access_nested_element(lst, indices):
    """Access element using list of indices."""
    element = lst
    for i in indices:
        element = element[i]
    return element


def sum_nested(lst):
    """Returns sum of all elements in nested list."""
    total = 0
    for i in lst:
        if isinstance(i, list):
            total += sum_nested(i)
        else:
            total += i
    return total


def remove_element(lst, elem):
    """Removes element from nested list."""
    result = []
    for i in lst:
        if isinstance(i, list):
            result.append(remove_element(i, elem))
        else:
            if i != elem:
                result.append(i)
    return result


def find_max(lst):
    """Find maximum element in nested list."""
    max_val = float('-inf')
    for i in lst:
        if isinstance(i, list):
            max_val = max(max_val, find_max(i))
        else:
            max_val = max(max_val, i)
    return max_val


def count_occurrences(lst, elem):
    """Counts occurrences in nested list."""
    count = 0
    for i in lst:
        if isinstance(i, list):
            count += count_occurrences(i, elem)
        else:
            if i == elem:
                count += 1
    return count


def deep_flatten(lst):
    """Flattens nested list of any depth."""
    result = []
    for i in lst:
        if isinstance(i, list):
            result.extend(deep_flatten(i))
        else:
            result.append(i)
    return result


def average_nested(lst):
    """Returns average of nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)
nested = [[1,2],[3,[4,5]],6]

print("Flatten:", flatten([[1,2],[3,4],[5]]))

Flatten: [1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**
Write a Python function that extracts a specific element from a nested list given its indices.
**• Requirements:**
 Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
 Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
print("Access:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]],[1,2]))

Access: 6


**3. Sum of All Elements in a Nested List:**
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
**• Requirements:**
 Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
 Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
print("Sum:", sum_nested(nested))

Sum: 21


**4. Remove Specific Element from a Nested List:**
Write a Python function that removes all occurrences of a specific element from a nested list.
**• Requirements:**
 Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
 Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].


In [ ]:
print("Remove element:", remove_element([[1,2],[3,2],[4,5]],2))

Remove element: [[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**
Write a Python function that finds the maximum element in a nested list (regardless of depth).
**• Requirements:**
 Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
 Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

21


In [ ]:
print("Max:", find_max(nested))

Max: 6


**6. Count Occurrences of an Element in a Nested List:**
Write a Python function that counts how many times a specific element appears in a nested list.
**• Requirements:**
 Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
 Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.


In [ ]:
print("Count:", count_occurrences([[1,2],[2,3],[2,4]],2))

Count: 3


**7. Flatten a List of Lists of Lists:**
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
**• Requirements:**
 Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
 Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
print("Deep flatten:", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**
Write a Python function that calculates the average of all elements in a nested list.
**• Requirements:**
 Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
 Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
print("Average:", average_nested([[1,2],[3,4],[5,6]]))

Average: 3.5




---



# To - Do - NumPy

# 10.1 Basic Vector and Matrix Operation with Numpy.

**Problem - 1: Array Creation:**

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
import numpy as np

# 1. Empty array 2x2
a = np.empty((2,2))
print("Empty Array:\n", a)

# 2. All ones array 4x2
b = np.ones((4,2))
print("\nOnes Array:\n", b)

# 3. Array filled with a value
c = np.full((3,3), 7)
print("\nFull Array:\n", c)

# 4. Zeros like array
d = np.zeros_like(c)
print("\nZeros Like:\n", d)

# 5. Ones like array
e = np.ones_like(c)
print("\nOnes Like:\n", e)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
f = np.array(new_list)
print("\nArray from List:", f)

Empty Array:
 [[7.49277992e-316 0.00000000e+000]
 [6.64489263e-310 6.64489228e-310]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones Like:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Array from List: [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

46


In [ ]:
# 1. Array from 10 to 49
arr1 = np.arange(10,50)
print(arr1)

# 2. 3x3 matrix from 0 to 8
arr2 = np.arange(9).reshape(3,3)
print(arr2)

# 3. Identity matrix
identity = np.eye(3)
print(identity)

# 4. Random array size 30 and mean
rand30 = np.random.random(30)
print("Mean:", rand30.mean())

# 5. 10x10 random array
rand10 = np.random.random((10,10))
print("Min:", rand10.min())
print("Max:", rand10.max())

# 6. Zero array size 10 and replace 5th element
z = np.zeros(10)
z[4] = 1
print(z)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

# 8. 2D array with border 1 and inside 0
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print(border)

# 9. Checkerboard pattern 8x8
checker = np.zeros((8,8))
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print(checker)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean: 0.47429331375471256
Min: 5.9834174487405356e-05
Max: 0.9767247602256575
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1 Add
print("Add:\n", x+y)

# 2 Subtract
print("Subtract:\n", x-y)

# 3 Multiply with integer
print("Multiply:\n", x*3)

# 4 Square
print("Square:\n", x**2)

# 5 Dot Products
print("v.w =", np.dot(v,w))
print("x.v =", np.dot(x,v))
print("x.y =\n", np.dot(x,y))

# 6 Concatenate
print("Row Concatenate:\n", np.concatenate((x,y),axis=0))
print("Column Concatenate:\n", np.concatenate((v.reshape(2,1),w.reshape(2,1)),axis=1))

# 7 Concatenate x and v
# Error occurs because dimensions are different
# x is 2D and v is 1D

Add:
 [[ 6  8]
 [10 13]]
Subtract:
 [[-4 -4]
 [-4 -3]]
Multiply:
 [[ 3  6]
 [ 9 15]]
Square:
 [[ 1  4]
 [ 9 25]]
v.w = 219
x.v = [29 77]
x.y =
 [[19 22]
 [50 58]]
Row Concatenate:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Column Concatenate:
 [[ 9 11]
 [10 12]]


**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

**Prove following with Numpy:**
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

**• Solve the following system of Linear equation using Inverse Methods.**

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

47


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1 Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A,A_inv)

print("A * A^-1 =\n", I)

# 2 Prove AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB=\n", AB)
print("BA=\n", BA)

# 3 Prove (AB)^T = B^T A^T
left = (AB).T
right = np.dot(B.T, A.T)

print("(AB)^T=\n", left)
print("B^T A^T=\n", right)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB=
 [[23 13]
 [51 29]]
BA=
 [[36 44]
 [13 16]]
(AB)^T=
 [[23 51]
 [13 29]]
B^T A^T=
 [[23 51]
 [13 29]]


# 10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.


In [ ]:
A = np.array([
[2,-3,1],
[1,-1,2],
[3,1,-1]
])

B = np.array([-1,-3,9])

# Using inverse
A_inv = np.linalg.inv(A)

X = np.dot(A_inv,B)

print("Solution [x,y,z]:", X)

Solution [x,y,z]: [ 2.  1. -2.]


In [ ]:
# NumPy Built-in Linear Solver
X = np.linalg.solve(A,B)

print("Solution using solve():", X)

Solution using solve(): [ 2.  1. -2.]


In [ ]:
import numpy as np
import time

In [ ]:
# Element-wise Addition
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [list1[i] + list2[i] for i in range(size)]

end = time.time()

print("Python List Addition Time:", end-start)


# NumPy
a = np.arange(size)
b = np.arange(size)

start = time.time()

result = a + b

end = time.time()

print("NumPy Addition Time:", end-start)

Python List Addition Time: 0.10695052146911621
NumPy Addition Time: 0.019106626510620117


In [ ]:
# Element-wise Multipication
start = time.time()

result = [list1[i] * list2[i] for i in range(size)]

end = time.time()

print("Python List Multiplication:", end-start)


start = time.time()

result = a * b

end = time.time()

print("NumPy Multiplication:", end-start)

Python List Multiplication: 0.10692358016967773
NumPy Multiplication: 0.01671314239501953


In [ ]:
# Dot Product
start = time.time()

dot = sum(list1[i] * list2[i] for i in range(size))

end = time.time()

print("Python Dot Product:", end-start)


start = time.time()

dot = np.dot(a,b)

end = time.time()

print("NumPy Dot Product:", end-start)

Python Dot Product: 0.11319160461425781
NumPy Dot Product: 0.0018529891967773438


In [ ]:
#Matrix Multipication
size = 200

A = np.random.rand(size,size)
B = np.random.rand(size,size)

start = time.time()

C = np.dot(A,B)

end = time.time()

print("NumPy Matrix Multiplication:", end-start)

NumPy Matrix Multiplication: 0.0011146068572998047
